/**
 * Maps body-highlighter SVG slugs → backend muscle names.
 * Single source of truth — used in Dashboard, ExerciseLibrary, and anywhere
 * else the body map widget appears.
 */
export const BODY_MAP_MAPPING = {
  'trapezius-left-front': 'traps',
  'trapezius-right-front': 'traps',
  'trapezius-left-back': 'traps',
  'trapezius-right-back': 'traps',
  'upper-back-left': 'middle back',
  'upper-back-right': 'middle back',
  'lower-back-left': 'lower back',
  'lower-back-right': 'lower back',
  'chest-left': 'chest',
  'chest-right': 'chest',
  'biceps-left': 'biceps',
  'biceps-right': 'biceps',
  'triceps-left-front': 'triceps',
  'triceps-right-front': 'triceps',
  'triceps-left-back': 'triceps',
  'triceps-right-back': 'triceps',
  'forearm-left-front': 'forearms',
  'forearm-right-front': 'forearms',
  'forearm-left-back': 'forearms',
  'forearm-right-back': 'forearms',
  'deltoids-left-front': 'shoulders',
  'deltoids-right-front': 'shoulders',
  'deltoids-left-back': 'shoulders',
  'deltoids-right-back': 'shoulders',
  'abs-upper': 'abdominals',
  'abs-lower': 'abdominals',
  'obliques-left': 'abdominals',
  'obliques-right': 'abdominals',
  'adductors-left-front': 'adductors',
  'adductors-right-front': 'adductors',
  'adductors-left-back': 'adductors',
  'adductors-right-back': 'adductors',
  'hamstring-left': 'hamstrings',
  'hamstring-right': 'hamstrings',
  'quadriceps-left': 'quadriceps',
  'quadriceps-right': 'quadriceps',
  'calves-left-front': 'calves',
  'calves-right-front': 'calves',
  'calves-left-back': 'calves',
  'calves-right-back': 'calves',
  'gluteal-left': 'glutes',
  'gluteal-right': 'glutes',
  'neck-left-front': 'neck',
  'neck-right-front': 'neck',
  'neck-left-back': 'neck',
  'neck-right-back': 'neck',
};
